### PR TITLE
Add Flake interface

### PR DESCRIPTION
**Pull request by worldofpeace**

### CODE REVIEW

**Comment by msteen** [comment]
I currently do not have the time to work on this project or test things related to flakes, but from what I have seen it looks good, so I will merge it for now.

**Comment by worldofpeace** [comment]
> I currently do not have the time to work on this project or test things related to flakes, but from what I have seen it looks good, so I will merge it for now.

Thanks, that is really okay. Yay merged :sparkles:

**Comment by colemickens** [comment]
Does this work for you @worldofpeace ? I can't get it to work and I don't think it's me.

**Comment by worldofpeace** [comment]
> Does this work for you @worldofpeace ? I can't get it to work and I don't think it's me.

It does work for me when using `nix build` and I get a symlink to the defaultPackage. Do you mean in another `flake.nix`?
If possible, could you paste what that would look like for you?

**Pull request merged**
